default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: review-book-development

test:
  <<: *default
  database: review-book-test

production:
  <<: *default
  database: review-book-production
  username: review-book
  password: <%= ENV['REVIEW-BOOK_DATABASE_PASSWORD'] %>
